Boundless QGIS 2.14.8 build

##### Mac #####

## Deps ##


QGIS version
2.14.8-Essen
QGIS code revision
<some 7-character hash>
Compiled against Qt
4.8.7
Running against Qt
4.8.7
Compiled against GDAL/OGR
2.1.2
Running against GDAL/OGR
2.1.2
Compiled against GEOS
3.5.0-CAPI-1.9.0
Running against GEOS
3.5.0-CAPI-1.9.0 r4084
PostgreSQL Client Version
9.5.4
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
PROJ.4 Version
493
QScintilla2 Version
2.9.3
This copy of QGIS writes debugging output.



## Providers ##

Available QGIS Data Provider Plugins
    WFS data provider
    Delimited text data provider
    GDAL provider
    GPS eXchange format provider
    GRASS 7 vector provider
    GRASS 7 raster provider
    Memory provider
    MSSQL spatial data provider
    OGR data provider (compiled against GDAL/OGR library version 2.1.2, running against GDAL/OGR library version 2.1.2)
    OWS meta provider
    PostgreSQL/PostGIS data provider
    SpatiaLite data provider
    Virtual layer data provider
    OGC Web Coverage Service version 1.0/1.1 data provider
    OGC Web Map Service version 1.3 data provider

Available QGIS Authentication Method Plugins
    Basic authentication
    Identity certificate authentication
    PKI PKCS#12 authentication
    PKI paths authentication

Available Qt Database Plugins
    QSQLITE
    QODBC3
    QODBC
    QPSQL7
    QPSQL
    QSPATIALITE

Available Qt Image Plugins
    Qt Image Plugin Search Paths
    /Library/Boundless/Cellar/qt-4/4.8.7/plugins
    /Library/Boundless/Cellar/qgis2-bdesk/2.14.8/QGIS.app/Contents/PlugIns/qgis
    bmp
    gif
    ico
    jpeg
    jpg
    mng
    pbm
    pgm
    png
    ppm
    svg
    svgz
    tga
    tif
    tiff
    xbm
    xpm