Boundless QGIS 2.14.1 build

##### Mac #####

## Deps ##

QGIS version   2.14.1-Essen            QGIS code revision  2b63af7 <-- could be different
Compiled against Qt 4.8.6              Running against Qt 4.8.6
Compiled against GDAL/OGR 2.0.2        Running against GDAL/OGR 2.0.2
Compiled against GEOS 3.4.2-CAPI-1.8.2 Running against GEOS 3.4.2-CAPI-1.8.2 r3921
PostgreSQL Client Version 9.4.1        SpatiaLite Version 4.2.0
QWT Version 6.0.2                      PROJ.4 Version 491
QScintilla2 Version 2.9                This copy of QGIS writes debugging output.

## Providers ##

Available QGIS Data Provider Plugins
  WFS data provider
  Delimited text data provider
  GDAL provider
  GPS eXchange format provider
  GRASS 7 vector provider
  GRASS 7 raster provider
  Memory provider
  MSSQL spatial data provider
  OGR data provider (compiled against GDAL/OGR library version 2.0.2, running against GDAL/OGR library version 2.0.2)
  OWS meta provider
  PostgreSQL/PostGIS data provider
  SpatiaLite data provider
  Virtual layer data provider
  OGC Web Coverage Service version 1.0/1.1 data provider
  OGC Web Map Service version 1.3 data provider

Available QGIS Authentication Method Plugins
  Basic authentication
  Identity certificate authentication
  PKI PKCS#12 authentication
  PKI paths authentication

Available Qt Database Plugins
  QSQLITE
  QODBC3
  QODBC
  QPSQL7
  QPSQL
  QSPATIALITE

Available Qt Image Plugins
Qt Image Plugin Search Paths
/Applications/QGIS.app/Contents/PlugIns
/Applications/QGIS.app/Contents/PlugIns/qgis
  bmp
  gif
  ico
  jpeg
  jpg
  pbm
  pgm
  png
  ppm
  svg
  svgz
  tif
  tiff
  xbm
  xpm
